In [1]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv("C:\\Users\\DELL\\Downloads\\archive (2)\\BBCNews.csv")

In [9]:
df.head()

,Unnamed: 0,descr,tags
0,0,chelsea sack mutu chelsea have sacked adrian ...,"sports, stamford bridge, football association,..."
1,1,record fails to lift lacklustre meet yelena i...,"sports, madrid, birmingham, france, scotland, ..."
2,2,edu describes tunnel fracas arsenals edu has ...,"sports, derby, brazil, tunnel fracasedu, food,..."
3,3,ogara revels in ireland victory ireland flyha...,"sports, bbc, united kingdom, ireland, brian o'..."
4,4,unclear future for striker baros liverpool fo...,"sports, liverpool, daily sport, millennium sta..."

In [10]:
df.shape

(2410, 3)

In [11]:
bbc_data=df.copy()

In [12]:
bbc_data

,Unnamed: 0,descr,tags
0,0,chelsea sack mutu chelsea have sacked adrian ...,"sports, stamford bridge, football association,..."
1,1,record fails to lift lacklustre meet yelena i...,"sports, madrid, birmingham, france, scotland, ..."
2,2,edu describes tunnel fracas arsenals edu has ...,"sports, derby, brazil, tunnel fracasedu, food,..."
3,3,ogara revels in ireland victory ireland flyha...,"sports, bbc, united kingdom, ireland, brian o'..."
4,4,unclear future for striker baros liverpool fo...,"sports, liverpool, daily sport, millennium sta..."
...,...,...,...
2405,2405,gm in crunch talks on fiat future fiat will m...,"business, zurich, fiat, reuters, the financial..."
2406,2406,uk firm faces venezuelan land row venezuelan ...,"agroflora, reuters, vestey group, venezuela, u..."
2407,2407,winndixie files for bankruptcy us supermarket...,"business, jacksonville, kraft foods, winn-dixi..."
2408,2408,yangtze electrics profits double yangtze elec...,"environment, business, yangtze electric power,..."
2409,2409,algeria hit by further gas riots algeria suff...,"politics, environment, algiers, el watan, alge..."

In [13]:
bbc_data.columns=["News_ID","Description","Tags"]

In [14]:
bbc_data

,News_ID,Description,Tags
0,0,chelsea sack mutu chelsea have sacked adrian ...,"sports, stamford bridge, football association,..."
1,1,record fails to lift lacklustre meet yelena i...,"sports, madrid, birmingham, france, scotland, ..."
2,2,edu describes tunnel fracas arsenals edu has ...,"sports, derby, brazil, tunnel fracasedu, food,..."
3,3,ogara revels in ireland victory ireland flyha...,"sports, bbc, united kingdom, ireland, brian o'..."
4,4,unclear future for striker baros liverpool fo...,"sports, liverpool, daily sport, millennium sta..."
...,...,...,...
2405,2405,gm in crunch talks on fiat future fiat will m...,"business, zurich, fiat, reuters, the financial..."
2406,2406,uk firm faces venezuelan land row venezuelan ...,"agroflora, reuters, vestey group, venezuela, u..."
2407,2407,winndixie files for bankruptcy us supermarket...,"business, jacksonville, kraft foods, winn-dixi..."
2408,2408,yangtze electrics profits double yangtze elec...,"environment, business, yangtze electric power,..."
2409,2409,algeria hit by further gas riots algeria suff...,"politics, environment, algiers, el watan, alge..."

In [15]:
bbc_data.isnull().sum()

News_ID        0
Description    0
Tags           0
dtype: int64

In [18]:
from langchain.docstore.document import Documnet

ImportError: cannot import name 'Documnet' from 'langchain.docstore.document' (C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\docstore\document.py)

In [17]:
!pip install torch==2.4.1+cpu torchvision==0.19.1+cpu torchaudio==2.4.0+cpu --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
Collecting torch==2.4.1+cpu
  Using cached https://download.pytorch.org/whl/cpu/torch-2.4.1%2Bcpu-cp310-cp310-win_amd64.whl (201.8 MB)
Collecting torchvision==0.19.1+cpu
  Using cached https://download.pytorch.org/whl/cpu/torchvision-0.19.1%2Bcpu-cp310-cp310-win_amd64.whl (1.3 MB)
Collecting torchaudio==2.4.0+cpu
  Using cached https://download-r2.pytorch.org/whl/cpu/torchaudio-2.4.0%2Bcpu-cp310-cp310-win_amd64.whl (2.4 MB)
Collecting typing-extensions>=4.8.0
  Obtaining dependency information for typing-extensions>=4.8.0 from https://download.pytorch.org/whl/typing_extensions-4.15.0-py3-none-any.whl.metadata
  Downloading https://download.pytorch.org/whl/typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Discarding https://download.pytorch.org/whl/typing_extensions-4.15.0-py3-none-any.whl (from https://download.pytorch.org/whl/cpu/typing-extensions/): Requested typing-extensions>=4.8.0 from https://download.pytorch.org/whl/typing_extensions-4.15.0-py3-none-any.whl (from torch==2.4.1+cpu) has inconsistent Name: expected 'typing-extensions', but metadata has 'typing_extensions'
  Obtaining dependency information for typing-extensions>=4.8.0 from https://download.pytorch.org/whl/typing_extensions-4.14.0-py3-none-any.whl.metadata
  Downloading https://download.pytorch.org/whl/typing_extensions-4.14.0-py3-none-any.whl.metadata (3.0 kB)
Discarding https://download.pytorch.org/whl/typing_extensions-4.14.0-py3-none-any.whl (from https://download.pytorch.org/whl/cpu/typing-extensions/): Requested typing-extensions>=4.8.0 from https://download.pytorch.org/whl/typing_extensions-4.14.0-py3-none-any.whl (from torch==2.4.1+cpu) has inconsistent Name: expected 'typing-extensions', but metadata has 'typing_extensions'
  Obtaining dependency information for typing-extensions>=4.8.0 from https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl.metadata
  Downloading https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Discarding https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl (from https://download.pytorch.org/whl/cpu/typing-extensions/): Requested typing-extensions>=4.8.0 from https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl (from torch==2.4.1+cpu) has inconsistent Name: expected 'typing-extensions', but metadata has 'typing_extensions'
  Downloading https://download.pytorch.org/whl/typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting filelock
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/76/91/7216b27286936c16f5b4d0c530087e4a54eead683e6b0b73dd0c64844af6/filelock-3.20.0-py3-none-any.whl.metadata
  Downloading filelock-3.20.0-py3-none-any.whl.metadata (2.1 kB)
Collecting jinja2
  Obtaining dependency information for jinja2 from https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl.metadata
  Downloading https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Discarding https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl (from https://download.pytorch.org/whl/cpu/jinja2/): Requested jinja2 from https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl (from torch==2.4.1+cpu) has inconsistent Name: expected 'jinja2', but metadata has 'Jinja2'
  Obtaining dependency information for jinja2 from https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl.metadata
  Downloading https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Discarding https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl#sha256=bc5dd2abb727a5319567b7a813e6a2e7318c39f4f487cfe6c89c6f9c7d25197d (from https://download.pytorch.org/whl/cpu/jinja2/): Requested jinja2 from https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl#sha256=bc5dd2abb727a5319567b7a813e6a2e7318c39f4f487cfe6c89c6f9c7d25197d (from torch==2.4.1+cpu) has inconsistent Name: expected 'jinja2', but metadata has 'Jinja2'
  Downloading https://download.pytorch.org/whl/Jinja2-3.1.3-py3-none-any.whl (133 kB)
     ---------------------------------------- 0.0/133.2 kB ? eta -:--:--
     -------- ------------------------------ 30.7/133.2 kB 1.4 MB/s eta 0:00:01
     -------------------------------------- 133.2/133.2 kB 1.6 MB/s eta 0:00:00
Collecting networkx
  Obtaining dependency information for networkx from https://files.pythonhosted.org/packages/b9/54/dd730b32ea14ea797530a4479b2ed46a6fb250f682a9cfb997e968bf0261/networkx-3.4.2-py3-none-any.whl.metadata
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting sympy
  Obtaining dependency information for sympy from https://files.pythonhosted.org/packages/a2/09/77d55d46fd61b4a135c444fc97158ef34a095e5681d0a6c10b75bf356191/sympy-1.14.0-py3-none-any.whl.metadata
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting fsspec
  Obtaining dependency information for fsspec from https://files.pythonhosted.org/packages/51/c7/b64cae5dba3a1b138d7123ec36bb5ccd39d39939f18454407e5468f4763f/fsspec-2025.12.0-py3-none-any.whl.metadata
  Downloading fsspec-2025.12.0-py3-none-any.whl.metadata (10 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Obtaining dependency information for pillow!=8.3.*,>=5.3.0 from https://files.pythonhosted.org/packages/92/c6/c2f2fc7e56301c21827e689bb8b0b465f1b52878b57471a070678c0c33cd/pillow-12.0.0-cp310-cp310-win_amd64.whl.metadata
  Downloading pillow-12.0.0-cp310-cp310-win_amd64.whl.metadata (9.0 kB)
Collecting numpy
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/a3/dd/4b822569d6b96c39d1215dbae0582fd99954dcbcf0c1a13c61783feaca3f/numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.8 kB 435.7 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.8 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 324.4 kB/s eta 0:00:00
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.

The conflict is caused by:
    The user requested torch==2.4.1+cpu
    torchvision 0.19.1+cpu depends on torch==2.4.1
    torchaudio 2.4.0+cpu depends on torch==2.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: Cannot install torch==2.4.1+cpu, torchaudio==2.4.0+cpu and torchvision==0.19.1+cpu because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

In [19]:
!pip install langchain

Collecting langchain
  Downloading langchain-1.2.12-py3-none-any.whl (112 kB)
     ---------------------------------------- 0.0/112.4 kB ? eta -:--:--
     ---------- ---------------------------- 30.7/112.4 kB 1.3 MB/s eta 0:00:01
     ------------- ----------------------- 41.0/112.4 kB 393.8 kB/s eta 0:00:01
     -------------------------------- --- 102.4/112.4 kB 653.6 kB/s eta 0:00:01
     ------------------------------------ 112.4/112.4 kB 654.7 kB/s eta 0:00:00
Collecting langchain-core<2.0.0,>=1.2.10
  Downloading langchain_core-1.2.19-py3-none-any.whl (503 kB)
     ---------------------------------------- 0.0/503.5 kB ? eta -:--:--
     ----- --------------------------------- 71.7/503.5 kB 1.9 MB/s eta 0:00:01
     --------- ---------------------------- 122.9/503.5 kB 2.4 MB/s eta 0:00:01
     --------- ---------------------------- 122.9/503.5 kB 2.4 MB/s eta 0:00:01
     --------- ---------------------------- 122.9/503.5 kB 2.4 MB/s eta 0:00:01
     ---------- ------------------------- 143.4/503.5 kB 652.5 kB/s eta 0:00:01
     ---------- ------------------------- 143.4/503.5 kB 652.5 kB/s eta 0:00:01
     ------------------- ---------------- 276.5/503.5 kB 896.4 kB/s eta 0:00:01
     ------------------- ---------------- 276.5/503.5 kB 896.4 kB/s eta 0:00:01
     ------------------- ---------------- 276.5/503.5 kB 896.4 kB/s eta 0:00:01
     ------------------- ---------------- 276.5/503.5 kB 896.4 kB/s eta 0:00:01
     ------------------- ---------------- 276.5/503.5 kB 896.4 kB/s eta 0:00:01
     ------------------- ---------------- 276.5/503.5 kB 896.4 kB/s eta 0:00:01
     ------------------- ---------------- 276.5/503.5 kB 896.4 kB/s eta 0:00:01
     ------------------------------------ 503.5/503.5 kB 734.0 kB/s eta 0:00:00
Collecting langgraph<1.2.0,>=1.1.1
  Downloading langgraph-1.1.2-py3-none-any.whl (167 kB)
     ---------------------------------------- 0.0/167.5 kB ? eta -:--:--
     ---------------- ---------------------- 71.7/167.5 kB 3.8 MB/s eta 0:00:01
     --------------------- ----------------- 92.2/167.5 kB 2.6 MB/s eta 0:00:01
     --------------------- ----------------- 92.2/167.5 kB 2.6 MB/s eta 0:00:01
     --------------------- ----------------- 92.2/167.5 kB 2.6 MB/s eta 0:00:01
     --------------------- ----------------- 92.2/167.5 kB 2.6 MB/s eta 0:00:01
     -------------------------- --------- 122.9/167.5 kB 450.6 kB/s eta 0:00:01
     ------------------------------------ 167.5/167.5 kB 529.6 kB/s eta 0:00:00
Collecting pydantic<3.0.0,>=2.7.4
  Downloading pydantic-2.12.5-py3-none-any.whl (463 kB)
     ---------------------------------------- 0.0/463.6 kB ? eta -:--:--
     -- ------------------------------------ 30.7/463.6 kB 1.4 MB/s eta 0:00:01
     ---- -------------------------------- 61.4/463.6 kB 825.8 kB/s eta 0:00:01
     -------- --------------------------- 112.6/463.6 kB 939.4 kB/s eta 0:00:01
     ----------- ------------------------ 153.6/463.6 kB 919.0 kB/s eta 0:00:01
     ---------------- --------------------- 204.8/463.6 kB 1.0 MB/s eta 0:00:01
     ---------------- --------------------- 204.8/463.6 kB 1.0 MB/s eta 0:00:01
     ---------------- --------------------- 204.8/463.6 kB 1.0 MB/s eta 0:00:01
     ------------------------ ----------- 317.4/463.6 kB 895.6 kB/s eta 0:00:01
     -------------------------------------- 463.6/463.6 kB 1.2 MB/s eta 0:00:00
Collecting typing-extensions<5.0.0,>=4.7.0
  Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
     ---------------------------------------- 0.0/44.6 kB ? eta -:--:--
     ---------------------------------------- 44.6/44.6 kB 2.1 MB/s eta 0:00:00
Collecting langsmith<1.0.0,>=0.3.45
  Downloading langsmith-0.7.17-py3-none-any.whl (359 kB)
     ---------------------------------------- 0.0/359.1 kB ? eta -:--:--
     ------ -------------------------------- 61.4/359.1 kB 1.7 MB/s eta 0:00:01
     ------- ------------------------------- 71.7/359.1 kB 1.3 MB/s eta 0:00:01
     ------- ------------------------------- 71.7/359.1 kB 1.3 MB/s eta 0:00:01
     ------- ------------------------------- 71.7/359.1 kB 1.3 MB/s eta 0:00:01
     ------------------------------ ------- 286.7/359.1 kB 1.3 MB/s eta 0:00:01
     --------------------------------- ---- 317.4/359.1 kB 1.2 MB/s eta 0:00:01
     --------------------------------- ---- 317.4/359.1 kB 1.2 MB/s eta 0:00:01
     --------------------------------- ---- 317.4/359.1 kB 1.2 MB/s eta 0:00:01
     -----------------------------------  358.4/359.1 kB 857.5 kB/s eta 0:00:01
     ------------------------------------ 359.1/359.1 kB 826.8 kB/s eta 0:00:00
Collecting uuid-utils<1.0,>=0.12.0
  Downloading uuid_utils-0.14.1-cp39-abi3-win_amd64.whl (187 kB)
     ---------------------------------------- 0.0/187.1 kB ? eta -:--:--
     -------- ------------------------------ 41.0/187.1 kB 2.0 MB/s eta 0:00:01
     ------------------------ ------------- 122.9/187.1 kB 1.8 MB/s eta 0:00:01
     -------------------------------------- 187.1/187.1 kB 1.6 MB/s eta 0:00:00
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0
  Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Collecting packaging>=23.2.0
  Downloading packaging-26.0-py3-none-any.whl (74 kB)
     ---------------------------------------- 0.0/74.4 kB ? eta -:--:--
     -------------------------------------- - 71.7/74.4 kB 3.8 MB/s eta 0:00:01
     ---------------------------------------- 74.4/74.4 kB 2.0 MB/s eta 0:00:00
Collecting pyyaml<7.0.0,>=5.3.0
  Downloading pyyaml-6.0.3-cp310-cp310-win_amd64.whl (158 kB)
     ---------------------------------------- 0.0/158.6 kB ? eta -:--:--
     -- ------------------------------------- 10.2/158.6 kB ? eta -:--:--
     -------------------------- ----------- 112.6/158.6 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 158.6/158.6 kB 1.4 MB/s eta 0:00:00
Collecting jsonpatch<2.0.0,>=1.33.0
  Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Collecting langgraph-checkpoint<5.0.0,>=2.1.0
  Downloading langgraph_checkpoint-4.0.1-py3-none-any.whl (50 kB)
     ---------------------------------------- 0.0/50.5 kB ? eta -:--:--
     ---------------------------------------- 50.5/50.5 kB 2.5 MB/s eta 0:00:00
Collecting xxhash>=3.5.0
  Using cached xxhash-3.6.0-cp310-cp310-win_amd64.whl (31 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.8
  Downloading langgraph_prebuilt-1.0.8-py3-none-any.whl (35 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0
  Downloading langgraph_sdk-0.3.11-py3-none-any.whl (94 kB)
     ---------------------------------------- 0.0/94.9 kB ? eta -:--:--
     ---------------------------------------- 94.9/94.9 kB 5.3 MB/s eta 0:00:00
Collecting pydantic-core==2.41.5
  Downloading pydantic_core-2.41.5-cp310-cp310-win_amd64.whl (2.0 MB)
     ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
      --------------------------------------- 0.0/2.0 MB 640.0 kB/s eta 0:00:04
     --- ------------------------------------ 0.2/2.0 MB 2.2 MB/s eta 0:00:01
     ----- ---------------------------------- 0.3/2.0 MB 2.2 MB/s eta 0:00:01
     ----- ---------------------------------- 0.3/2.0 MB 2.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/2.0 MB 1.5 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.0 MB 1.2 MB/s eta 0:00:02
     -------- ------------------------------- 0.4/2.0 MB 1.3 MB/s eta 0:00:02
     ---------- ----------------------------- 0.5/2.0 MB 1.4 MB/s eta 0:00:02
     ------------ --------------------------- 0.6/2.0 MB 1.5 MB/s eta 0:00:01
     -------------- ------------------------- 0.7/2.0 MB 1.5 MB/s eta 0:00:01
     -------------- ------------------------- 0.7/2.0 MB 1.5 MB/s eta 0:00:01
     ---------------- ----------------------- 0.8/2.0 MB 1.5 MB/s eta 0:00:01
     ----------------- ---------------------- 0.9/2.0 MB 1.5 MB/s eta 0:00:01
     ------------------- -------------------- 1.0/2.0 MB 1.5 MB/s eta 0:00:01
     --------------------- ------------------ 1.1/2.0 MB 1.5 MB/s eta 0:00:01
     --------------------- ------------------ 1.1/2.0 MB 1.5 MB/s eta 0:00:01
     ---------------------- ----------------- 1.1/2.0 MB 1.4 MB/s eta 0:00:01
     ------------------------- -------------- 1.3/2.0 MB 1.5 MB/s eta 0:00:01
     --------------------------- ------------ 1.4/2.0 MB 1.6 MB/s eta 0:00:01
     ---------------------------- ----------- 1.4/2.0 MB 1.6 MB/s eta 0:00:01
     ----------------------------- ---------- 1.5/2.0 MB 1.5 MB/s eta 0:00:01
     ------------------------------ --------- 1.5/2.0 MB 1.5 MB/s eta 0:00:01
     -------------------------------- ------- 1.6/2.0 MB 1.4 MB/s eta 0:00:01
     --------------------------------- ------ 1.7/2.0 MB 1.4 MB/s eta 0:00:01
     ----------------------------------- ---- 1.8/2.0 MB 1.5 MB/s eta 0:00:01
     ----------------------------------- ---- 1.8/2.0 MB 1.5 MB/s eta 0:00:01
     ----------------------------------- ---- 1.8/2.0 MB 1.5 MB/s eta 0:00:01
     ----------------------------------- ---- 1.8/2.0 MB 1.5 MB/s eta 0:00:01
     ----------------------------------- ---- 1.8/2.0 MB 1.5 MB/s eta 0:00:01
     ------------------------------------ --- 1.8/2.0 MB 1.3 MB/s eta 0:00:01
     ------------------------------------ --- 1.8/2.0 MB 1.3 MB/s eta 0:00:01
     ------------------------------------ --- 1.8/2.0 MB 1.3 MB/s eta 0:00:01
     ------------------------------------ --- 1.8/2.0 MB 1.3 MB/s eta 0:00:01
     ---------------------------------------  2.0/2.0 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------- 2.0/2.0 MB 1.2 MB/s eta 0:00:00
Collecting annotated-types>=0.6.0
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting typing-inspection>=0.4.2
  Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Collecting jsonpointer>=1.9
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Collecting ormsgpack>=1.12.0
  Using cached ormsgpack-1.12.2-cp310-cp310-win_amd64.whl (117 kB)
Collecting orjson>=3.11.5
  Using cached orjson-3.11.7-cp310-cp310-win_amd64.whl (125 kB)
Collecting httpx>=0.25.2
  Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
     ---------------------------------------- 0.0/73.5 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/73.5 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/73.5 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/73.5 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/73.5 kB ? eta -:--:--
     -------------------------------------- 73.5/73.5 kB 288.9 kB/s eta 0:00:00
Collecting requests>=2.0.0
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     ---------------------------------------- 0.0/64.7 kB ? eta -:--:--
     ---------------------------------------- 64.7/64.7 kB 1.8 MB/s eta 0:00:00
Collecting zstandard>=0.23.0
  Using cached zstandard-0.25.0-cp310-cp310-win_amd64.whl (506 kB)
Collecting requests-toolbelt>=1.0.0
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Collecting httpcore==1.*
  Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
     ---------------------------------------- 0.0/78.8 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/78.8 kB ? eta -:--:--
     ------------------- ------------------ 41.0/78.8 kB 487.6 kB/s eta 0:00:01
     -------------------------------------- 78.8/78.8 kB 548.4 kB/s eta 0:00:00
Collecting anyio
  Downloading anyio-4.12.1-py3-none-any.whl (113 kB)
     ---------------------------------------- 0.0/113.6 kB ? eta -:--:--
     -------------- ------------------------ 41.0/113.6 kB 1.9 MB/s eta 0:00:01
     ----------------------- ------------- 71.7/113.6 kB 975.2 kB/s eta 0:00:01
     -------------------------------------- 113.6/113.6 kB 1.1 MB/s eta 0:00:00
Collecting certifi
  Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
     ---------------------------------------- 0.0/153.7 kB ? eta -:--:--
     -- ------------------------------------- 10.2/153.7 kB ? eta -:--:--
     -- ------------------------------------- 10.2/153.7 kB ? eta -:--:--
     ------- ----------------------------- 30.7/153.7 kB 330.3 kB/s eta 0:00:01
     -------------- ---------------------- 61.4/153.7 kB 365.7 kB/s eta 0:00:01
     -------------- ---------------------- 61.4/153.7 kB 365.7 kB/s eta 0:00:01
     ---------------------- -------------- 92.2/153.7 kB 350.1 kB/s eta 0:00:01
     ----------------------- ------------ 102.4/153.7 kB 328.0 kB/s eta 0:00:01
     ---------------------------- ------- 122.9/153.7 kB 380.5 kB/s eta 0:00:01
     --------------------------------- -- 143.4/153.7 kB 370.8 kB/s eta 0:00:01
     ------------------------------------ 153.7/153.7 kB 353.3 kB/s eta 0:00:00
Collecting idna
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     ---------------------------------------- 0.0/71.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/71.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/71.0 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/71.0 kB ? eta -:--:--
     ---------------- --------------------- 30.7/71.0 kB 325.1 kB/s eta 0:00:01
     --------------------- ---------------- 41.0/71.0 kB 279.3 kB/s eta 0:00:01
     -------------------------------- ----- 61.4/71.0 kB 363.1 kB/s eta 0:00:01
     -------------------------------------- 71.0/71.0 kB 353.3 kB/s eta 0:00:00
Collecting h11>=0.16
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.5-cp310-cp310-win_amd64.whl (142 kB)
     ---------------------------------------- 0.0/142.9 kB ? eta -:--:--
     -- ------------------------------------- 10.2/142.9 kB ? eta -:--:--
     -------- ------------------------------ 30.7/142.9 kB 1.3 MB/s eta 0:00:01
     --------------- --------------------- 61.4/142.9 kB 544.7 kB/s eta 0:00:01
     ---------------------------- ------- 112.6/142.9 kB 819.2 kB/s eta 0:00:01
     ------------------------------------ 142.9/142.9 kB 771.3 kB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     ---------------------------------------- 0.0/131.6 kB ? eta -:--:--
     ------------------ -------------------- 61.4/131.6 kB 1.6 MB/s eta 0:00:01
     --------------------- ----------------- 71.7/131.6 kB 1.3 MB/s eta 0:00:01
     --------------------------------- -- 122.9/131.6 kB 901.1 kB/s eta 0:00:01
     ------------------------------------ 131.6/131.6 kB 860.6 kB/s eta 0:00:00
Collecting exceptiongroup>=1.0.2
  Downloading exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Installing collected packages: zstandard, xxhash, uuid-utils, urllib3, typing-extensions, tenacity, pyyaml, packaging, ormsgpack, orjson, jsonpointer, idna, h11, charset_normalizer, certifi, annotated-types, typing-inspection, requests, pydantic-core, jsonpatch, httpcore, exceptiongroup, requests-toolbelt, pydantic, anyio, httpx, langsmith, langgraph-sdk, langchain-core, langgraph-checkpoint, langgraph-prebuilt, langgraph, langchain
Successfully installed annotated-types-0.7.0 anyio-4.12.1 certifi-2026.2.25 charset_normalizer-3.4.5 exceptiongroup-1.3.1 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 idna-3.11 jsonpatch-1.33 jsonpointer-3.0.0 langchain-1.2.12 langchain-core-1.2.19 langgraph-1.1.2 langgraph-checkpoint-4.0.1 langgraph-prebuilt-1.0.8 langgraph-sdk-0.3.11 langsmith-0.7.17 orjson-3.11.7 ormsgpack-1.12.2 packaging-26.0 pydantic-2.12.5 pydantic-core-2.41.5 pyyaml-6.0.3 requests-2.32.5 requests-toolbelt-1.0.0 tenacity-9.1.4 typing-extensions-4.15.0 typing-inspection-0.4.2 urllib3-2.6.3 uuid-utils-0.14.1 xxhash-3.6.0 zstandard-0.25.0

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
!pip install chromadb